/**
 * Test: Full pipeline with Ed25519 signed authorization.
 * This proves:
 * 1. Unsigned authorization still works (optional mode)
 * 2. Signed authorization is verified and recorded
 * 3. Invalid signature is rejected (fail-closed)
 */
import { readFileSync } from "node:fs";

// Load Brian's keypair (generated by the test earlier)
const secretKey = readFileSync("/home/ubuntu/rio-system/gateway/data/keys/brian.k.rasmussen.sec.hex", "utf-8").trim();
const publicKey = readFileSync("/home/ubuntu/rio-system/gateway/data/keys/brian.k.rasmussen.pub.hex", "utf-8").trim();

// Import tweetnacl and crypto
const nacl = (await import("tweetnacl")).default;
const { createHash } = await import("node:crypto");

const BASE = "http://localhost:4400";

async function post(path, body) {
  const res = await fetch(`${BASE}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  return { status: res.status, data: await res.json() };
}

async function get(path) {
  const res = await fetch(`${BASE}${path}`);
  return await res.json();
}

function signPayload(payload, secretKeyHex) {
  const sk = Buffer.from(secretKeyHex, "hex");
  const msg = Buffer.from(payload, "utf-8");
  const sig = nacl.sign.detached(msg, sk);
  return Buffer.from(sig).toString("hex");
}

console.log("=== Ed25519 Pipeline Test ===\n");
console.log(`Brian's public key: ${publicKey.substring(0, 32)}...`);

// ---------------------------------------------------------------
// Test A: Signed authorization (should succeed)
// ---------------------------------------------------------------
console.log("\n--- Test A: Ed25519 Signed Authorization ---");

// Step 1: Submit intent
const intentA = await post("/intent", {
  action: "send_email",
  agent_id: "MANUS",
  description: "Ed25519 signed authorization test",
  parameters: { to: "test@example.com", subject: "Ed25519 Test" },
  confidence: 95,
});
console.log(`1. Intent: ${intentA.data.intent_id}`);

// Step 2: Govern
await post("/govern", { intent_id: intentA.data.intent_id });
console.log("2. Governed");

// Step 3: Sign and authorize
const sigTimestamp = new Date().toISOString();
const payload = JSON.stringify({
  intent_id: intentA.data.intent_id,
  action: "send_email",
  decision: "approved",
  signer_id: "brian.k.rasmussen",
  timestamp: sigTimestamp,
});
const signature = signPayload(payload, secretKey);
console.log(`3. Signature: ${signature.substring(0, 32)}...`);

const authA = await post("/authorize", {
  intent_id: intentA.data.intent_id,
  decision: "approved",
  authorized_by: "brian.k.rasmussen",
  signature: signature,
  signature_timestamp: sigTimestamp,
});
console.log(`4. Auth status: ${authA.status}`);
console.log(`   Ed25519 signed: ${authA.data.ed25519_signed}`);
console.log(`   Result: ${authA.data.ed25519_signed ? "PASS" : "FAIL"}`);

// ---------------------------------------------------------------
// Test B: Invalid signature (should be rejected — fail closed)
// ---------------------------------------------------------------
console.log("\n--- Test B: Invalid Signature (should fail) ---");

const intentB = await post("/intent", {
  action: "send_email",
  agent_id: "MANUS",
  description: "Invalid signature test",
  parameters: { to: "test@example.com" },
  confidence: 95,
});
await post("/govern", { intent_id: intentB.data.intent_id });

const badSig = "a".repeat(128); // Fake signature
const authB = await post("/authorize", {
  intent_id: intentB.data.intent_id,
  decision: "approved",
  authorized_by: "brian.k.rasmussen",
  signature: badSig,
  signature_timestamp: new Date().toISOString(),
});
console.log(`1. Auth status: ${authB.status}`);
console.log(`   Reason: ${authB.data.reason || authB.data.error}`);
console.log(`   Result: ${authB.status === 403 ? "PASS (correctly rejected)" : "FAIL"}`);

// ---------------------------------------------------------------
// Test C: Unsigned authorization (should still work in optional mode)
// ---------------------------------------------------------------
console.log("\n--- Test C: Unsigned Authorization (optional mode) ---");

const intentC = await post("/intent", {
  action: "read_file",
  agent_id: "MANUS",
  description: "Unsigned auth test",
  parameters: { path: "/tmp/test.txt" },
  confidence: 99,
});
await post("/govern", { intent_id: intentC.data.intent_id });

const authC = await post("/authorize", {
  intent_id: intentC.data.intent_id,
  decision: "approved",
  authorized_by: "brian.k.rasmussen",
  // No signature
});
console.log(`1. Auth status: ${authC.status}`);
console.log(`   Ed25519 signed: ${authC.data.ed25519_signed}`);
console.log(`   Result: ${authC.status === 200 && !authC.data.ed25519_signed ? "PASS (accepted unsigned)" : "FAIL"}`);

// ---------------------------------------------------------------
// Verify ledger
// ---------------------------------------------------------------
console.log("\n--- Ledger Verification ---");
const health = await get("/health");
console.log(`Ledger entries: ${health.ledger.entries}`);
console.log(`Chain valid: ${health.ledger.chain_valid}`);

// Check PostgreSQL
console.log("\n=== All tests complete ===");
