import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {createICAReference,reopenICAReference} from '../../local-field/ica/journey.mjs';
import {ReferenceWorkspace} from '../../local-field/ica/workspace.mjs';
import {renderICA} from '../../local-field/ica/surface.mjs';
import {generateKeypair,signPayload} from '../../security/ed25519.mjs';
import {canonicalizeArgs} from '../../security/token-manager.mjs';
const act=(f,a)=>f.journey.dispatch({action:a,expected_revision:f.journey.view().revision,request_id:randomUUID()});
function setup(t,fixture='normal'){const d=mkdtempSync(join(tmpdir(),'f1-review-')),root=join(d,'field');t.after(()=>rmSync(d,{recursive:true,force:true}));return createICAReference({root,fixture});}
function dump(db){return Object.fromEntries(db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all().map(({name})=>[name,db.prepare(`SELECT * FROM "${name}" ORDER BY rowid`).all()]));}
test('prepared reentry never acquires runtime or writes recovery/standing to any table',t=>{const f=setup(t);act(f,'refresh');act(f,'delegate');f.close();const db=new DatabaseSync(join(f.root,'field.sqlite'),{readOnly:true});t.after(()=>db.close());const before=dump(db);const r=reopenICAReference({root:f.root});r.close();assert.deepEqual(dump(db),before);assert.equal(r.journey.view().consequence.typed_account.lease_condition,'UNKNOWN');});
test('replacement after accepted reporting cannot carry old successor rights into a new inhabitant',t=>{const f=setup(t,'occupant-replacement');t.after(()=>f.close());for(const a of ['refresh','delegate','revoke','return','accept-report','replace'])act(f,a);const v=f.journey.view();assert.equal(v.settlement,null);assert.equal(v.successor,null);assert.ok(!v.allowed_commands.includes('admit-account'));assert.ok(v.archived_research[0].prior_account.settlement);assert.match(renderICA(v,'test'),/Observatory/);});
test('root signature cannot manufacture an owner-issued Return from coordinate names',t=>{const d=mkdtempSync(join(tmpdir(),'f1-invented-')),w=new ReferenceWorkspace({root:join(d,'field')});t.after(()=>{w.close();rmSync(d,{recursive:true,force:true});});const p=w.prepare('note');w.runtime.admit(p.passage);const r={kind:'ReturnArtifact',return_id:'invented',passage_id:p.passage.body.passage_id,return_completeness:'COMPLETE',reporting_accounts:['ATTEMPT_ACCOUNT','OBSERVATION_ACCOUNT','OUTCOME_ACCOUNT','LIMITS_ACCOUNT'].map(coordinate=>({coordinate,account:{}}))};assert.throws(()=>w.captureReports(r,{kind:'ResearchReturnArtifact',provenance:{native_return_ref:'invented'},residue:[]}),/ISSUED_RETURN_ARTIFACT_REQUIRED/);});
test('mutable settlement index cannot substitute invented lineage for the recorded settlement',t=>{const f=setup(t);t.after(()=>f.close());for(const a of ['refresh','delegate','start','return','accept-report'])act(f,a);const s=f.journey.view().settlement,db=new DatabaseSync(join(f.root,'field.sqlite'));try{db.prepare('UPDATE state SET body=? WHERE kind=? AND id=?').run(JSON.stringify({...s,candidate_ref:'invented',return_ref:'invented',residue_refs:[]}),'reporting_settlement',s.settlement_id);}finally{db.close();}assert.throws(()=>act(f,'admit-account'),/CUSTODY/);assert.equal(f.journey.view().successor,null);});
test('anchor/definition substitution cannot authenticate a fabricated retained room',t=>{const f=setup(t);act(f,'refresh');f.close();const db=new DatabaseSync(join(f.root,'field.sqlite'));const attacker=generateKeypair();try{const a=JSON.parse(db.prepare('SELECT body FROM records WHERE kind=? AND id=?').get('anchor','sourcepoint').body);a.public_key_hex=attacker.publicKey;db.prepare('UPDATE records SET body=? WHERE kind=? AND id=?').run(JSON.stringify(a),'anchor','sourcepoint');const def=JSON.parse(db.prepare('SELECT body FROM records WHERE kind=? AND id=?').get('field','definition').body);def.signature=signPayload(canonicalizeArgs(def.body),attacker.secretKey);db.prepare('UPDATE records SET body=? WHERE kind=? AND id=?').run(JSON.stringify(def),'field','definition');}finally{db.close();}const snap=JSON.parse(readFileSync(join(f.root,'ica-checkpoint.json'),'utf8'));snap.signature=signPayload(canonicalizeArgs(snap.body),attacker.secretKey);writeFileSync(join(f.root,'ica-checkpoint.json'),JSON.stringify(snap));assert.throws(()=>reopenICAReference({root:f.root}),/ROOM_CONSTITUTION_CUSTODY|SIGNATURE/);});
