/** Human rendering reuses both existing projections; no interpretation or authority engine. */
import { randomUUID } from 'node:crypto';
import { validateICAView } from './journey.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const COMMANDS={refresh:'Read latest conditions',what:'What is this?',why:'Why does it appear?',delegate:'Authorize this Research',start:'Start this Research',return:'Read Research’s Return',
 revoke:'Withdraw future use',acknowledge:'Check withdrawal acknowledgement',keep:'Keep this finding for orientation',perimeter:'Move retained items between NOW and Perimeter',compare:'Read the later source frame',replace:'Replace Research inhabitant',
 'accept-report':'Accept this reporting account', 'admit-account':'Carry this account into subsequent orientation'};
const PHASE={OBSERVATORY:'Your Observatory',AUTHORIZED:'Research authorized; no attempt yet',ATTEMPTED:'Research attempted; readback is pending',RETURNED:'Research has returned',
 PARTIAL_RETURN:'Return is partial',HOLD:'Research is waiting',DENY:'Research is denied',REVOKED:'Future-use withdrawal recorded',EXPIRED:'This Research authorization has expired'};
const REPORTS={ATTEMPT_ACCOUNT:'Attempt report',OBSERVATION_ACCOUNT:'Observation report',OUTCOME_ACCOUNT:'Outcome report',LIMITS_ACCOUNT:'Limits report'};
const METRICS={available_time_margin:'Available time',meeting_density:'Meeting density',buffer_compression:'Buffer compression',open_pr_age:'Open PR age',review_latency:'Review wait',commit_velocity:'Commit activity'};
export function renderICA(view,csrf,{message=''}={}){
 validateICAView(view);
 const buttons=view.allowed_commands.map(action=>`<form method="post" action="/command" data-command="${action}"><input type="hidden" name="action" value="${action}"><input type="hidden" name="expected_revision" value="${view.revision}"><input type="hidden" name="request_id" value="${randomUUID()}"><input type="hidden" name="csrf" value="${esc(csrf)}"><button type="submit"${action==='revoke'?' class="withdraw"':''}>${COMMANDS[action]}</button></form>`).join('');
 const sections=view.instrument.sections.map(s=>`<section class="weather"><h3>${esc(s.title)}</h3><ul>${s.lines.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`).join('');
 const signals=view.show_why?`<details><summary>Evidence for the observable contributors</summary><p>Normalized source signals retain direction and change per hour. They do not measure personal stress or establish future events.</p><div class="table-wrap"><table><thead><tr><th>Signal</th><th>State</th><th>Movement</th><th>Extraction window</th></tr></thead><tbody>${view.reading.signal_manifest.map(s=>`<tr><td>${METRICS[s.signal_type]}</td><td>${s.magnitude.toFixed(2)}</td><td>${esc(s.direction.toLowerCase())} (${s.rate_of_change.toFixed(4)}/hour)</td><td>${esc(s.observation_window.start)} → ${esc(s.observation_window.end)}<details><summary>Signal lineage</summary><p>${esc(s.source_domain)} · ${esc(s.extractor_id)} · version ${esc(s.extractor_version)}</p><code>${esc(s.signal_id)}</code></details></td></tr>`).join('')}</tbody></table></div></details>`:'';
 const claims=view.consequence?.claims.map(c=>`<article class="claim" data-claim="${c.code}"><h3>${esc(c.code.toLowerCase().replaceAll('_',' ').replace(/^./,x=>x.toUpperCase()))}</h3><p>${esc(c.text)}</p><details><summary>What establishes this</summary><p>${esc(c.contract)}</p><code>${esc(c.basis_ref)}</code></details></article>`).join('')??'';
 const returned=view.consequence?.typed_account.returned,missing=returned?returned.required_reports.filter(r=>!returned.reporting_accounts.some(a=>a.coordinate===r)):[];
 const partial=missing.length?`<aside class="limit"><strong>Return is partial.</strong><p>Required reporting accounts still missing: ${missing.map(r=>REPORTS[r]).join(', ')}. Readback knowledge and reporting completeness are separate.</p></aside>`:'';
 const outcomes=returned?`<section><h3>What remains with the human</h3><ul>${returned.outstanding_obligations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p>No settlement or further authorization is supplied by this Return.</p></section>`:'';
 const research=view.research,rr=view.research_return,established=research?.findings.filter(x=>x.status==='ESTABLISHED').length??0;
 const findings=research?`<section aria-label="Research findings"><h2>Research findings</h2><p>${established===2?'Two findings established; one remains unknown.':established===0?'The available history does not establish these findings.':`${established} findings established within the replay.`}</p><p>We cannot yet tell whether this has happened before beyond the authorized history.</p>${research.findings.map(f=>`<article class="claim"><h3>${esc(f.status==='ESTABLISHED'?'Established in the replay':'We do not yet know')}</h3><p>${esc(f.text)}</p><details><summary>Basis and limits for this finding</summary><p>${esc(f.provenance.scope)}</p><p>Source lineage: ${f.provenance.reading_refs.map(esc).join(', ')}</p><code>${esc(f.finding_id)}</code></details></article>`).join('')}${rr?`<p>Research reporting: ${esc(rr.return_completeness.toLowerCase())}. Investigative outcome: ${esc(rr.outcome_assessment.toLowerCase())}. The local note’s readback is accounted separately.</p>${rr.work_condition==='REVOKED'?'<p>You withdrew this assignment. Future authorized exercise is disabled after local acknowledgement; earlier findings and any committed effects remain attributable.</p>':''}`:''}</section>`:'';
 const gate=view.research_gate?`<aside class="limit"><h3>${view.research_gate.disposition==='HOLD'?'This Research is waiting':'That consequence is outside Research'}</h3><p>${esc(view.research_gate.clearance_condition)}</p><p>This affects the requested Research consequence. You can still inspect the Observatory.</p><details><summary>Current decision and its basis</summary><p>${esc(view.research_gate.reason)} · native reason: ${esc(view.research_gate.native_disposition?.reason??view.research_gate.native_condition.reason)}</p><code>${view.research_gate.native_disposition?'ConstitutionalDisposition:'+esc(view.research_gate.native_disposition.decision_id):'CCMCurrentPreflight:'+esc(view.research_gate.native_condition.passage_id)}</code></details></aside>`:'';
 const remainder=view.perimeter.items.map(x=>`<li><strong>${esc(x.attention.toLowerCase())}</strong>: ${esc(x.text)}<details><summary>Why this remains</summary><p>${esc(x.remainder_kind)} · retained; no discharge recorded</p><code>${esc(x.basis_ref)}</code></details></li>`).join('');
 const perimeter=view.perimeter.items.length?`<section aria-label="Perimeter"><h2>Perimeter</h2><p>Unfinished items remain accounted for. Moving them changes attention, not authority or evidence.</p><details${view.perimeter.position==='NOW'?' open':''}><summary>${view.perimeter.position==='PERIMETER'?'Retained at the Perimeter':'Relevant unfinished items'} (${view.perimeter.items.length})</summary><ul>${remainder}</ul></details></section>`:'';
 const lumen=`<p class="muted" aria-label="LUMEN">LUMEN — ${esc(view.lumen.state.toLowerCase())}: ${esc(view.lumen.state==='OCCLUDED'?'a required basis is blocked':view.lumen.state==='UNKNOWN'?'the available history cannot answer':view.lumen.state==='SHADOWED'?'conditions are visible; important gaps remain':'the declared condition is visible')}. This describes visibility and supplies no permission.</p>`;
 const replacement=view.archived_research.length?`<p class="limit">New Research inhabitant. The Research Office charter is unchanged. The earlier delegation was withdrawn; ${view.delegation?'this inhabitant received a fresh delegation.':'this inhabitant needs a fresh delegation.'}</p>`:'';
 const settlement=view.settlement?`<section aria-label="Reporting account acceptance"><h2>Reporting account accepted</h2><p>You accepted the reporting account only. This does not establish occurrence, achieve the research objective, or discharge retained obligations.</p><p>${esc(view.research_return.occurrence_knowledge==='UNKNOWN'?'Whether the note occurred remains unknown.':'The separate note readback retains its stated limits.')} Research outcome: ${esc(view.research_return.outcome_assessment.toLowerCase())}.</p><details><summary>Your separate acceptance and its scope</summary><pre>${esc(JSON.stringify(view.settlement,null,2))}</pre></details>${view.successor?'<p>You separately admitted this account to subsequent orientation. No new Research or execution was authorized.</p>':''}</section>`:'';
 const divergence=view.divergence?`<aside class="limit"><strong>Later conditions differ from the candidate outlook.</strong><p>Earlier interpretation remains in lineage. The earlier pressure differential and the later improving front are both inspectable; no history was rewritten.</p><details><summary>Compare the two attributable readings</summary><code>${esc(view.divergence.prior_reading_ref)} → ${esc(view.divergence.current_reading_ref)}</code><p>${esc(view.divergence.scope)}</p></details></aside>`:'';
 const fixture=view.reference_fixture==='normal'?'Standard reference path':view.reference_fixture==='unknown'?'Declared fixture: independent observation is unavailable; this does not prove a physical network partition':view.reference_fixture==='partial'?'Declared fixture: two required reporting accounts are withheld':`Declared fixture: native ${view.reference_fixture.toUpperCase()} policy`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ICA-RR-001 · Observatory</title><style>
 :root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0c1521;color:#e9eef5;font:16px/1.55 system-ui,sans-serif}main{max-width:1100px;margin:0 auto;padding:32px 24px 60px}header{border-bottom:1px solid #355167;padding-bottom:24px}h1{font-size:34px;margin:8px 0}h2{font-size:24px;margin:30px 0 14px}h3{font-size:18px;color:#a7e1e5}p{margin:8px 0}.eyebrow{letter-spacing:.09em;font-size:12px;color:#aac0d5}.muted,footer{color:#afc1d3}.limit{border-left:4px solid #ccae73;padding:12px 18px;background:#1c2937;margin:18px 0}.weather-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.weather,.claim{border:1px solid #345067;border-radius:12px;padding:18px;background:#122233}.weather h3,.claim h3{margin-top:0}.controls{display:flex;gap:10px;flex-wrap:wrap;padding:20px 0}form{margin:0}button{border:1px solid #87cdd5;border-radius:8px;background:#204955;color:#fff;padding:12px 16px;font:inherit;cursor:pointer}button:hover{background:#2d6473}button:focus-visible,summary:focus-visible{outline:3px solid #e7cf95;outline-offset:3px}.withdraw{background:#3b3534;border-color:#b6a08d}details{margin:14px 0;padding:12px;border:1px solid #344e62;border-radius:8px}summary{cursor:pointer;color:#b5dce5}code,pre{font:12px/1.5 monospace;white-space:pre-wrap;overflow-wrap:anywhere}ul{padding-left:22px}.claims{display:grid;gap:12px}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid #344e62;vertical-align:top}.table-wrap{overflow:auto}.answers{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.answer h3{margin-bottom:8px}footer{border-top:1px solid #344e62;margin-top:32px;padding-top:20px}@media(max-width:700px){main{padding:20px 16px}.weather-grid,.answers{grid-template-columns:1fr}h1{font-size:28px}.controls form,button{width:100%}}
 </style></head><body><main><header><p class="eyebrow">ONE · ICA-RR-001 · BOUNDED REFERENCE REALIZATION</p><h1>Observatory</h1><p>See what is changing. Ask Research to investigate within a scope you can understand. Read what it can establish, then decide what follows.</p><p class="muted">One Place: Observatory · One Office: Research · One Instrument: Metascope</p></header>
 <aside class="limit"><strong>Reference source replay — not connected to your live Calendar or Git.</strong><p>${esc(view.source_contract)}. ${esc(fixture)}.</p><p>Controller: a local reference human session. This does not establish production human identity.</p></aside>
 ${message?`<p role="alert" class="limit">${esc(message)}</p>`:''}${view.reentry?'<aside class="limit"><strong>Retained account</strong><p>This authenticated historical account preserves where you left the journey. No permission, delegation, or execution lease was revived. A new assignment requires a fresh reference session and human choice.</p></aside>':''}<h2>${view.reentry?'Where you left this journey':PHASE[view.phase]}</h2>${lumen}${replacement}${divergence}
 <p>${esc(view.answers[1].answer)}</p>${view.show_what?`<p class="limit">${esc(view.answers[2].answer)}</p>`:''}
 <div class="weather-grid">${sections}</div>${signals}
 <section aria-label="Research scope"><h2>One bounded Research</h2><p>Research may compare the authorized Calendar/Git timing history, ask whether this has happened before, and write one local research note, at most 4096 bytes. It may not contact anyone, schedule work, or delegate further.</p><p>Findings describe the available replay. Storing the note, establishing its readback, and answering the research question are distinct burdens. Whether its possible bottleneck will occur remains unresolved.</p><p>Authorizing Research records permission for a signed invocation commitment. Starting it is a separate request, checked against current Office, inhabitant, delegation and authority.</p></section>
 <nav class="controls" aria-label="Available human choices">${buttons}</nav>
 ${view.disposition&&!view.consequence?`<aside class="limit"><p>${esc(view.answers[5].answer)}</p><details><summary>Why this passage cannot proceed</summary><p>${esc(view.disposition.reason??view.disposition.rationale??view.disposition.disposition)}</p><code>ConstitutionalDisposition:${esc(view.disposition.decision_id)}</code></details></aside>`:''}
 ${gate}${findings}${view.consequence?`<section aria-label="Research Return"><h2>The local note’s execution account</h2>${partial}<div class="claims">${claims}</div>${outcomes}</section>`:''}${settlement}${perimeter}
 <section><h2>Your eight lived answers</h2><div class="answers">${view.answers.map(a=>`<article class="answer"><h3>${esc(a.question)}</h3><p>${esc(a.answer)}</p></article>`).join('')}</div></section>
 <details><summary>Paired journey and machine register</summary><p>Each human step has its machine correspondent. These references explain the visible claims; they supply no new authority.</p><ol>${view.register.map(e=>`<li><strong>${esc(e.human_action)}</strong> · ${esc(e.transition)}<br><code>${esc(e.artifact_ref)}</code><details><summary>Inspect the attributable artifact</summary><pre>${esc(JSON.stringify(e.machine_artifact,null,2))}</pre></details></li>`).join('')}</ol></details>
 <details><summary>Inspect the typed current account</summary><p>Journey ${esc(view.journey_id)} · revision ${view.revision}. Authenticated restart retains orientation and lineage. Operative leases are never restored from display data.</p><pre>${esc(JSON.stringify(view,null,2))}</pre><a href="/account.json">Open machine-readable current account</a></details>
 <footer><p>Architectural Conformance + Lived Simplicity = Reference Realization Candidate</p><p>The radar changes visibility. A Return supplies an account. Any next action requires its own fresh authority. Successful transformation supplies no standing.</p></footer></main></body></html>`;
}
