/**
 * RIO Gateway — Signer Management Routes (WS-010: Identity Binding)
 *
 * These endpoints manage Ed25519 signer identities.
 * Area 1: Now gated by principal roles instead of owner-only JWT.
 *
 * Endpoints:
 *   POST /api/signers/generate-keypair  — Generate keypair (root_authority or meta_governor)
 *   POST /api/signers/register          — Register an externally-generated public key (root_authority or meta_governor)
 *   GET  /api/signers                   — List all registered signers (any principal)
 *   GET  /api/signers/:signer_id        — Get signer details (any principal)
 *   DELETE /api/signers/:signer_id      — Revoke a signer (root_authority or meta_governor)
 *
 * Security:
 *   - Private keys are NEVER stored on the server
 *   - generate-keypair returns the private key exactly once
 *   - Only the public key is persisted in authorized_signers table
 *   - Write operations require root_authority or meta_governor role
 *   - Read operations require any authenticated principal
 */
import { Router } from "express";
import { requireAuth } from "../security/oauth.mjs";
import { generateKeypair } from "../security/ed25519.mjs";
import {
  registerSigner,
  getSigner,
  getSignerPublicKey,
  listSigners,
  revokeSigner,
} from "../security/identity-binding.mjs";
import { appendEntry, getEntryCount } from "../ledger/ledger-pg.mjs";
import {
  requireRole,
  requirePrincipal,
} from "../security/principals.mjs";

const router = Router();

// =========================================================================
// POST /api/signers/generate-keypair
// Generate a new Ed25519 keypair. The private key is returned ONCE.
// The public key is stored in the authorized_signers table.
// Area 1: Requires root_authority or meta_governor role.
// =========================================================================
router.post(
  "/generate-keypair",
  requireRole("root_authority", "meta_governor"),
  async (req, res) => {
    try {
      const { signer_id, display_name, role } = req.body;

      if (!signer_id) {
        return res.status(400).json({
          error: "Missing required field: signer_id",
          hint: "Provide a unique identifier for the signer (e.g., 'brian.k.rasmussen').",
        });
      }

      // Check if already registered
      const existing = getSigner(signer_id);
      if (existing) {
        return res.status(409).json({
          error: `Signer already registered: ${signer_id}`,
          hint: "Each signer_id can only be registered once. Revoke first to re-register.",
        });
      }

      // Generate Ed25519 keypair
      const keypair = generateKeypair();

      // Store ONLY the public key in PostgreSQL
      const signer = await registerSigner({
        signer_id,
        public_key_hex: keypair.publicKey,
        display_name: display_name || signer_id,
        role: role || "approver",
      });

      // Log to ledger with principal attribution
      appendEntry({
        intent_id: "00000000-0000-0000-0000-000000000000",
        action: "signer_registered",
        agent_id: req.principal?.principal_id || req.user?.sub || "unknown",
        status: "system",
        detail: `Ed25519 signer registered: ${signer_id} (keypair generated by gateway). Public key: ${keypair.publicKey.substring(0, 16)}... Principal: ${req.principal?.principal_id || "unknown"}`,
      });

      console.log(
        `[RIO Identity] Keypair generated for ${signer_id} by principal ${req.principal?.principal_id || "unknown"}. Private key returned — NEVER STORED.`
      );

      // Return the private key ONCE — it is never stored on the server
      res.status(201).json({
        signer_id: signer.signer_id,
        display_name: signer.display_name,
        role: signer.role,
        registered_at: signer.registered_at,
        public_key_hex: keypair.publicKey,
        secret_key_hex: keypair.secretKey,
        _warning:
          "SAVE THIS PRIVATE KEY NOW. It will NEVER be shown again. The gateway does NOT store private keys.",
        _instructions: {
          step_1: "Copy secret_key_hex to a secure location (password manager, hardware key, etc.)",
          step_2: "Use this key to sign authorization payloads via buildSignaturePayload() + signPayload()",
          step_3: "Include the signature in POST /authorize requests",
          step_4: "The gateway verifies signatures against the stored public key",
        },
      });
    } catch (err) {
      console.error(`[RIO Identity] Generate keypair error: ${err.message}`);
      res.status(500).json({ error: err.message });
    }
  }
);

// =========================================================================
// POST /api/signers/register
// Register an externally-generated Ed25519 public key.
// Area 1: Requires root_authority or meta_governor role.
// =========================================================================
router.post("/register", requireRole("root_authority", "meta_governor"), async (req, res) => {
  try {
    const { signer_id, public_key_hex, display_name, role } = req.body;

    if (!signer_id || !public_key_hex) {
      return res.status(400).json({
        error: "Missing required fields: signer_id, public_key_hex",
        hint: "Generate a keypair offline, then register the public key here.",
      });
    }

    const signer = await registerSigner({
      signer_id,
      public_key_hex,
      display_name: display_name || signer_id,
      role: role || "approver",
    });

    // Log to ledger with principal attribution
    appendEntry({
      intent_id: "00000000-0000-0000-0000-000000000000",
      action: "signer_registered",
      agent_id: req.principal?.principal_id || req.user?.sub || "unknown",
      status: "system",
      detail: `Ed25519 signer registered: ${signer_id} (external public key). Public key: ${public_key_hex.substring(0, 16)}... Principal: ${req.principal?.principal_id || "unknown"}`,
    });

    console.log(
      `[RIO Identity] External public key registered for ${signer_id} by principal ${req.principal?.principal_id || "unknown"}`
    );

    res.status(201).json({
      signer_id: signer.signer_id,
      display_name: signer.display_name,
      role: signer.role,
      registered_at: signer.registered_at,
      public_key_hex: signer.public_key_hex,
      _note: "Only the public key is stored. The private key remains with the signer.",
    });
  } catch (err) {
    console.error(`[RIO Identity] Register error: ${err.message}`);
    res.status(err.message.includes("already registered") ? 409 : 500).json({
      error: err.message,
    });
  }
});

// =========================================================================
// GET /api/signers
// List all registered signers (public keys only, never private keys).
// Area 1: Requires any authenticated principal.
// =========================================================================
router.get("/", requirePrincipal, (req, res) => {
  try {
    const signers = listSigners();
    res.json({
      signers,
      count: signers.length,
    });
  } catch (err) {
    res.status(500).json({ error: "Internal error listing signers." });
  }
});

// =========================================================================
// GET /api/signers/:signer_id
// Get a specific signer's public key and metadata.
// Area 1: Requires any authenticated principal.
// =========================================================================
router.get("/:signer_id", requirePrincipal, (req, res) => {
  try {
    const signer = getSigner(req.params.signer_id);
    if (!signer) {
      return res.status(404).json({
        error: `Signer not found: ${req.params.signer_id}`,
      });
    }
    res.json({
      signer_id: req.params.signer_id,
      ...signer,
    });
  } catch (err) {
    res.status(500).json({ error: "Internal error reading signer." });
  }
});

// =========================================================================
// DELETE /api/signers/:signer_id
// Revoke a signer — removes their public key from authorized_signers.
// Area 1: Requires root_authority or meta_governor role.
// =========================================================================
router.delete(
  "/:signer_id",
  requireRole("root_authority", "meta_governor"),
  async (req, res) => {
    try {
      const signer_id = req.params.signer_id;

      // Prevent self-revocation
      if (signer_id === req.principal?.principal_id || signer_id === req.user?.sub) {
        return res.status(400).json({
          error: "Cannot revoke your own signer identity.",
          hint: "Another authorized principal must revoke your key.",
        });
      }

      const revoked = await revokeSigner(signer_id);
      if (!revoked) {
        return res.status(404).json({
          error: `Signer not found: ${signer_id}`,
        });
      }

      // Log to ledger with principal attribution
      appendEntry({
        intent_id: "00000000-0000-0000-0000-000000000000",
        action: "signer_revoked",
        agent_id: req.principal?.principal_id || req.user?.sub || "unknown",
        status: "system",
        detail: `Ed25519 signer revoked: ${signer_id} by principal ${req.principal?.principal_id || "unknown"}`,
      });

      console.log(
        `[RIO Identity] Signer revoked: ${signer_id} by principal ${req.principal?.principal_id || "unknown"}`
      );

      res.json({
        signer_id,
        status: "revoked",
        revoked_by: req.principal?.principal_id || req.user?.sub,
        timestamp: new Date().toISOString(),
      });
    } catch (err) {
      console.error(`[RIO Identity] Revoke error: ${err.message}`);
      res.status(500).json({ error: "Internal error revoking signer." });
    }
  }
);

export default router;
