"""
RIO Compliance Report Generator
════════════════════════════════
Generates a formatted compliance report from runner output.

Usage:
  python runner/generate_compliance_report.py [input_json] [output_path]

If no input is provided, runs the compliance suite first.
"""

import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def generate_markdown_report(report: dict) -> str:
    """Convert a compliance report JSON to Markdown."""
    lines = []
    meta = report.get("_meta", {})
    summary = report.get("summary", {})
    results = report.get("results", [])

    lines.append("# RIO Compliance Report")
    lines.append("")
    lines.append(f"**Generated:** {meta.get('generated_at', 'unknown')}")
    lines.append(f"**Runner:** {meta.get('runner', 'unknown')}")
    lines.append(f"**Version:** {meta.get('version', 'unknown')}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Scenarios | {summary.get('total', 0)} |")
    lines.append(f"| Passed | {summary.get('passed', 0)} |")
    lines.append(f"| Failed | {summary.get('failed', 0)} |")
    lines.append(f"| Overall | **{summary.get('overall', 'UNKNOWN')}** |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Scenario Results")
    lines.append("")

    for r in results:
        status_icon = "PASS" if r.get("passFail") == "PASS" else "FAIL"
        lines.append(f"### {r.get('scenario', '?')}: {status_icon}")
        lines.append("")
        lines.append(f"**Claim:** {r.get('claim', '')}")
        lines.append("")
        lines.append(f"**Evidence:**")
        lines.append("```json")
        lines.append(json.dumps(r.get("evidence", {}), indent=2))
        lines.append("```")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by RIO Compliance Report Generator*")

    return "\n".join(lines)


def main():
    if len(sys.argv) >= 2 and os.path.exists(sys.argv[1]):
        with open(sys.argv[1]) as f:
            report = json.load(f)
    else:
        from runner.run_tests import run_compliance_suite
        report = run_compliance_suite()

    md = generate_markdown_report(report)

    if len(sys.argv) >= 3:
        output_path = sys.argv[2]
    else:
        os.makedirs("artifacts/compliance", exist_ok=True)
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%S")
        output_path = f"artifacts/compliance/compliance-report-{timestamp}.md"

    with open(output_path, "w") as f:
        f.write(md)

    print(f"Report written to: {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
