/**
 * ReceiptExport — Shared component for downloading receipts as JSON or PDF.
 *
 * Usage:
 *   <ReceiptExport receipt={receiptObject} label="v2 Receipt" />
 */

import { useState } from "react";

interface ReceiptExportProps {
  receipt: Record<string, any>;
  label?: string;
}

function downloadJSON(data: Record<string, any>, filename: string) {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function downloadPDF(data: Record<string, any>, filename: string) {
  // Build a simple text-based PDF using a minimal PDF structure
  const lines: string[] = [];
  lines.push("RIO GOVERNED EXECUTION RECEIPT");
  lines.push("=".repeat(50));
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push(`Protocol Version: ${data.protocol_version || "v2"}`);
  lines.push("");

  // Flatten the receipt into key-value pairs
  for (const [key, value] of Object.entries(data)) {
    if (typeof value === "object" && value !== null) {
      lines.push(`${key}:`);
      for (const [k, v] of Object.entries(value)) {
        lines.push(`  ${k}: ${v}`);
      }
    } else {
      lines.push(`${key}: ${value}`);
    }
  }

  lines.push("");
  lines.push("=".repeat(50));
  lines.push("This receipt was generated by the RIO Runtime Intelligence Orchestration system.");
  lines.push("Verify at: /verify");

  // Use a simple text file with .txt extension since we can't generate real PDF client-side
  // without a library. For a proper PDF, we'd use a server endpoint.
  const text = lines.join("\n");
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.replace(".pdf", ".txt");
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function ReceiptExport({ receipt, label = "Receipt" }: ReceiptExportProps) {
  const [jsonDone, setJsonDone] = useState(false);
  const [pdfDone, setPdfDone] = useState(false);

  const receiptId = receipt.receipt_id || receipt.receiptId || "receipt";
  const jsonFilename = `rio-${receiptId}.json`;
  const pdfFilename = `rio-${receiptId}.txt`;

  return (
    <div className="flex items-center gap-2">
      <span className="text-[10px] font-medium" style={{ color: "#6b7280" }}>
        Export:
      </span>
      <button
        onClick={() => {
          downloadJSON(receipt, jsonFilename);
          setJsonDone(true);
          setTimeout(() => setJsonDone(false), 2000);
        }}
        className="px-2 py-1 text-[10px] font-medium rounded border transition-colors duration-200 hover:bg-white/5"
        style={{
          color: jsonDone ? "#22c55e" : "#b8963e",
          borderColor: jsonDone ? "#22c55e33" : "oklch(0.72 0.1 85 / 20%)",
          backgroundColor: "transparent",
        }}
      >
        {jsonDone ? "Downloaded!" : "JSON"}
      </button>
      <button
        onClick={() => {
          downloadPDF(receipt, pdfFilename);
          setPdfDone(true);
          setTimeout(() => setPdfDone(false), 2000);
        }}
        className="px-2 py-1 text-[10px] font-medium rounded border transition-colors duration-200 hover:bg-white/5"
        style={{
          color: pdfDone ? "#22c55e" : "#9ca3af",
          borderColor: pdfDone ? "#22c55e33" : "oklch(0.72 0.1 85 / 20%)",
          backgroundColor: "transparent",
        }}
      >
        {pdfDone ? "Downloaded!" : "TXT"}
      </button>
    </div>
  );
}
